//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNet3dsToolkit.Core.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNet3dsToolkit.Core.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File at the given path in the ROM could not be found: &quot;{0}&quot;.
        /// </summary>
        internal static string ErrorRomFileNotFound {
            get {
                return ResourceManager.GetString("ErrorRomFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking....
        /// </summary>
        internal static string LoadingUnpacking {
            get {
                return ResourceManager.GetString("LoadingUnpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARM7 Overlay Table.
        /// </summary>
        internal static string NdsRom_Analysis_ARM7OverlaySection {
            get {
                return ResourceManager.GetString("NdsRom_Analysis_ARM7OverlaySection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARM7 Binary.
        /// </summary>
        internal static string NdsRom_Analysis_ARM7Section {
            get {
                return ResourceManager.GetString("NdsRom_Analysis_ARM7Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARM9 Overlay Table.
        /// </summary>
        internal static string NdsRom_Analysis_ARM9OverlaySection {
            get {
                return ResourceManager.GetString("NdsRom_Analysis_ARM9OverlaySection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARM9 Binary.
        /// </summary>
        internal static string NdsRom_Analysis_ARM9Section {
            get {
                return ResourceManager.GetString("NdsRom_Analysis_ARM9Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAT.
        /// </summary>
        internal static string NdsRom_Analysis_FATSection {
            get {
                return ResourceManager.GetString("NdsRom_Analysis_FATSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Data.
        /// </summary>
        internal static string NdsRom_Analysis_FileSection {
            get {
                return ResourceManager.GetString("NdsRom_Analysis_FileSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FNT.
        /// </summary>
        internal static string NdsRom_Analysis_FNTSection {
            get {
                return ResourceManager.GetString("NdsRom_Analysis_FNTSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string NdsRom_Analysis_HeaderSection {
            get {
                return ResourceManager.GetString("NdsRom_Analysis_HeaderSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string NdsRom_Analysis_IconSection {
            get {
                return ResourceManager.GetString("NdsRom_Analysis_IconSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string NdsRom_Analysis_UnknownSection {
            get {
                return ResourceManager.GetString("NdsRom_Analysis_UnknownSection", resourceCulture);
            }
        }
    }
}
